repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-byte-order-marker
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.4
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
  - id: mypy
    name: Run type checks
    verbose: true
    args:
      - "--ignore-missing-imports"
      - "--install-types"
      - "--non-interactive"
      - "--python-version=3.11"
- repo: local
  hooks:
  - id: migrations-check
    language: system
    name: Check for uncreated migrations.
    entry: bash -c "./manage.py makemigrations --check --dry-run"
    types: ["python"]
    pass_filenames: false
